---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/hg3ads37/teste.3adsux.com.br/
    - /bin/cp -f index.html $DEPLOYPATH
    - /bin/cp -f enviar.php $DEPLOYPATH
    - /bin/cp -f og-image.jpg $DEPLOYPATH
    - /bin/cp -f robots.txt $DEPLOYPATH
    - /bin/cp -f sitemap.xml $DEPLOYPATH
    - /bin/cp -f .htaccess $DEPLOYPATH
